[package]
name = "rental-impl"
version = "0.4.14"
license = "MIT/Apache-2.0"
authors = ["Jameson Ernst <jameson@jpernst.com>"]
description = "An implementation detail of rental. Should not be used directly."
repository = "https://github.com/jpernst/rental"
documentation = "https://docs.rs/rental"
homepage = "https://www.jpernst.com"

[lib]
proc-macro = true

[dependencies]
procedural-masquerade = "=0.1.2"
quote = "0.3.15"
syn = { version = "0.11.10", features = ["full", "fold"] }
