[package]
name = "rental"
version = "0.3.5"
license = "MIT/Apache-2.0"
authors = ["Jameson Ernst <jameson@jpernst.com>"]
description = "A macro to generate self-borrowing structs, plus premade types for convenience."
keywords = ["lifetime", "ownership", "borrowing", "reference", "self"]
categories = ["rust-patterns", "no-std"]
repository = "https://github.com/jpernst/rental"
documentation = "https://docs.rs/rental"

[features]
default = ["std"]
std = ["stable_deref_trait/std"]

[dependencies]
stable_deref_trait = { version = "1.0.0", default-features = false}
