[package]
name = "rental"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Jameson Ernst <jameson@jpernst.com>"]
description = "A macro to generate self-borrowing structs."
repository = "https://github.com/jpernst/rental"
